
services:
  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks:
      - cohort16_network
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    restart: unless-stopped

  tomcat:
    build: .
    image: tomcat:acada
    ports:
      - "8082:8080"
    networks:
      - cohort16_network
    container_name: tomcat

  nexus:
    image: klo2k/nexus3
    container_name: nexus
    ports:
      - "8081:8081"
    networks:
      - cohort16_network
    volumes:
      - nexus_data:/nexus-data
    restart: unless-stopped

  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - "8090:8080"
      - "50000:50000"
    networks:
      - cohort16_network
    container_name: jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-data:/var/jenkins_home

networks:
  cohort16_network:
    external: true

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  nexus_data:
  jenkins-data:
